import { createSlice } from "@reduxjs/toolkit"; // Import createSlice from Redux Toolkit

// Create the auth slice using createSlice
const authSlice = createSlice({
    name: "auth", // Name of the slice
    initialState: {
        isLoggedIn: false // Initial state for the auth slice
    },

    // Reducers for handling actions
    reducers: {
        // Reducer for handling login action
        login: (state) => {
            state.isLoggedIn = true; // Set isLoggedIn to true when login action is dispatched
        },
    }
});

// Export the actions generated by createSlice
export const {
    login // Export the login action
} = authSlice.actions;

// Export the auth slice reducer as the default export
export default authSlice.reducer;
