import { createSlice } from "@reduxjs/toolkit"; // Import createSlice from Redux Toolkit

// Create a slice of the Redux store for managing todos
const todoSlice = createSlice({
    name: "todos", // Name of the slice
    initialState: {
        allTodos: [] // Initial state with an empty array of todos
    },

    // Reducers to handle different actions related to todos
    reducers: {
        // Reducer to add a new todo
        addTodo: (state, action) => {
            // Spread the current todos and add the new todo from the action payload
            state.allTodos = [...state.allTodos, action.payload.todoTobeAdded];
        },
        // Reducer to remove a todo
        removeTodo: (state, action) => {
            // Replace the current todos with the new array from the action payload
            state.allTodos = action.payload.newTodoArray;
        },
        // Reducer to edit a todo
        editTodo: (state, action) => {
            // Replace the current todos with the new array from the action payload
            state.allTodos = action.payload.newTodoArray;
        }
    }
});

// Export the action creators generated by createSlice
export const {
    addTodo,
    removeTodo,
    editTodo
} = todoSlice.actions;

// Export the reducer function generated by createSlice
export default todoSlice.reducer;
